# Generated by Django 4.1 on 2024-10-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indian", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TblCuisine",
            fields=[
                ("cuisine_id", models.AutoField(primary_key=True, serialize=False)),
                ("cuisine_name", models.CharField(max_length=200)),
            ],
            options={"db_table": "tbl_cuisine", "managed": False,},
        ),
        migrations.CreateModel(
            name="TblCustomerReview",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("review_text", models.CharField(max_length=500)),
            ],
            options={"db_table": "tbl_customer_review", "managed": False,},
        ),
        migrations.CreateModel(
            name="TblDishClassification",
            fields=[
                ("dish_class_id", models.AutoField(primary_key=True, serialize=False)),
                ("dish_class_name", models.CharField(max_length=100)),
                (
                    "dish_css_class",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={"db_table": "tbl_dish_classification", "managed": False,},
        ),
        migrations.CreateModel(
            name="TblMenu",
            fields=[
                ("menu_dish_id", models.AutoField(primary_key=True, serialize=False)),
                ("menu_dish_name", models.CharField(max_length=100)),
                ("menu_dish_cost", models.IntegerField()),
                (
                    "menu_dish_description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "menu_dish_pic_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("prog_name", models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={"db_table": "tbl_menu", "managed": False,},
        ),
        migrations.CreateModel(
            name="TblQuantityMetrics",
            fields=[
                ("metric_id", models.AutoField(primary_key=True, serialize=False)),
                ("metric_name", models.CharField(max_length=20)),
            ],
            options={"db_table": "tbl_quantity_metrics", "managed": False,},
        ),
        migrations.CreateModel(
            name="TblUser",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=200)),
                ("user_password", models.CharField(max_length=500)),
                ("user_first_name", models.CharField(max_length=200)),
                ("user_last_name", models.CharField(max_length=200)),
                ("user_gender", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "user_customer_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "user_business_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={"db_table": "tbl_user", "managed": False,},
        ),
        migrations.CreateModel(
            name="TblUserContactInfo",
            fields=[
                (
                    "user_contact_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("user_contact_value", models.CharField(max_length=500)),
                ("user_contact_default", models.BooleanField(blank=True, null=True)),
            ],
            options={"db_table": "tbl_user_contact_info", "managed": False,},
        ),
        migrations.CreateModel(
            name="TblUserContactType",
            fields=[
                (
                    "user_contact_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("user_contact_type_value", models.CharField(max_length=100)),
            ],
            options={"db_table": "tbl_user_contact_type", "managed": False,},
        ),
        migrations.CreateModel(
            name="TblUserOrder",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_date", models.DateTimeField()),
                ("order_total", models.FloatField(blank=True, null=True)),
            ],
            options={"db_table": "tbl_user_order", "managed": False,},
        ),
        migrations.CreateModel(
            name="TblUserOrderItems",
            fields=[
                ("order_items_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_item_quantity", models.IntegerField()),
                ("order_item_price", models.FloatField()),
            ],
            options={"db_table": "tbl_user_order_items", "managed": False,},
        ),
        migrations.CreateModel(
            name="BreakfastMenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menu_dish_name", models.CharField(max_length=100)),
                ("menu_dish_description", models.TextField()),
                ("menu_dish_cost", models.DecimalField(decimal_places=2, max_digits=6)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Breakfast Menu Item",
                "verbose_name_plural": "Breakfast Menu Items",
            },
        ),
    ]
