# Generated by Django 4.1 on 2024-10-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indian", "0002_tblcuisine_tblcustomerreview_tbldishclassification_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="breakfastmenuitem", name="id",),
        migrations.AddField(
            model_name="breakfastmenuitem",
            name="menu_dish_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
