# Generated by Django 4.1 on 2025-05-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indian", "0003_remove_breakfastmenuitem_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                ("conf_id", models.AutoField(primary_key=True, serialize=False)),
                ("conf_description", models.CharField(max_length=255)),
                ("conf_value", models.TextField()),
            ],
        ),
    ]
