--
-- PostgreSQL database dump
--

-- Dumped from database version 12.22 (Ubuntu 12.22-0ubuntu0.20.04.4)
-- Dumped by pg_dump version 12.22 (Ubuntu 12.22-0ubuntu0.20.04.4)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: get_customer_reviews(); Type: FUNCTION; Schema: public; Owner: foods
--

CREATE FUNCTION public.get_customer_reviews() RETURNS TABLE(review_id integer, user_id integer, user_first_name character varying, user_gender character varying, review_text character varying)
    LANGUAGE plpgsql
    AS $$
BEGIN
    RETURN QUERY
    SELECT 
		cr.review_id,
		u.user_id,
		u.user_first_name,
		u.user_gender,
		cr.review_text
	FROM tbl_customer_review cr
		 INNER JOIN tbl_user u ON cr.user_id = u.user_id;
END;
$$;


ALTER FUNCTION public.get_customer_reviews() OWNER TO foods;

--
-- Name: get_menu_items_func(); Type: FUNCTION; Schema: public; Owner: foods
--

CREATE FUNCTION public.get_menu_items_func() RETURNS TABLE(menu_dish_id integer, is_active character varying, menu_dish_name character varying, menu_dish_cost numeric, discounted_price numeric, cuisine_name character varying, dish_class_name character varying, dish_css_class character varying, menu_dish_description character varying, menu_dish_pic_path character varying, menu_extras character varying, menu_dish_seq integer)
    LANGUAGE plpgsql
    AS $$

DECLARE 
    discount NUMERIC;  -- allow decimals like 0.10 for 10%
BEGIN
    SELECT CAST(conf_value AS NUMERIC)
    INTO discount
    FROM indian_configuration
    WHERE conf_description = 'Discount';

    -- If no discount is found, default to 0
    IF discount IS NULL THEN
        discount := 0;
    END IF;

    RETURN QUERY
    SELECT
        m.menu_dish_id,
		m.is_active,
        m.menu_dish_name,
        m.menu_dish_cost,
        CASE 
		    WHEN discount = 0 THEN 0
		    ELSE ROUND(CAST(m.menu_dish_cost * (1 - discount / 100) AS NUMERIC), 2)
		END AS discounted_price,
		c.cuisine_name,
        dc.dish_class_name,
        dc.dish_css_class,
        m.menu_dish_description,
        m.menu_dish_pic_path,
        m.menu_extras,
		m.menu_dish_seq
    FROM
        tbl_menu m
        INNER JOIN tbl_cuisine c ON c.cuisine_id = m.menu_cuisine_id
        INNER JOIN tbl_dish_classification dc ON dc.dish_class_id = m.menu_dish_class_id;

END;
$$;


ALTER FUNCTION public.get_menu_items_func() OWNER TO foods;

--
-- Name: get_sub_menu_items_func(); Type: FUNCTION; Schema: public; Owner: foods
--

CREATE FUNCTION public.get_sub_menu_items_func() RETURNS TABLE(menu_item_id integer, menu_dishs_id integer, menu_dishs_name character varying, order_items_price numeric, activeyn character varying, discounted_price numeric)
    LANGUAGE plpgsql
    AS $$

DECLARE 
    discount NUMERIC;  -- allow decimals like 0.10 for 10%
BEGIN
    SELECT CAST(conf_value AS NUMERIC)
    INTO discount
    FROM indian_configuration
    WHERE conf_description = 'Discount';

    -- If no discount is found, default to 0
    IF discount IS NULL THEN
        discount := 0;
    END IF;

    RETURN QUERY
    SELECT
        menu_items_id,
		menu_dish_id,
        menu_dish_name,
        order_item_price,
		is_active,
        CASE 
		    WHEN discount = 0 THEN 0
		    ELSE ROUND(CAST(order_item_price * (1 - discount / 100) AS NUMERIC), 2)
		END AS discounted_price
    FROM
        tbl_sub_menu m;
END;
$$;


ALTER FUNCTION public.get_sub_menu_items_func() OWNER TO foods;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO foods;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO foods;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO foods;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO foods;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO foods;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO foods;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO foods;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO foods;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO foods;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO foods;

--
-- Name: django_site; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.django_site (
    id integer NOT NULL,
    domain character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.django_site OWNER TO foods;

--
-- Name: django_site_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.django_site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: indian_breakfastmenuitem; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.indian_breakfastmenuitem (
    menu_dish_name character varying(100) NOT NULL,
    menu_dish_description text NOT NULL,
    menu_dish_cost numeric(6,2) NOT NULL,
    is_available boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    menu_dish_id integer NOT NULL
);


ALTER TABLE public.indian_breakfastmenuitem OWNER TO foods;

--
-- Name: indian_configuration; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.indian_configuration (
    conf_id integer NOT NULL,
    conf_description character varying(255) NOT NULL,
    conf_value text NOT NULL
);


ALTER TABLE public.indian_configuration OWNER TO foods;

--
-- Name: indian_configuration_conf_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.indian_configuration ALTER COLUMN conf_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.indian_configuration_conf_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_app_conf; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.tbl_app_conf (
    app_conf_id integer NOT NULL,
    app_conf_name character varying(100) NOT NULL,
    app_conf_value character varying(300) NOT NULL
);


ALTER TABLE public.tbl_app_conf OWNER TO foods;

--
-- Name: tbl_app_conf_app_conf_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.tbl_app_conf ALTER COLUMN app_conf_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tbl_app_conf_app_conf_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_conf; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.tbl_conf (
    conf_id integer NOT NULL,
    conf_description character varying(500) NOT NULL,
    conf_value character varying(5000) NOT NULL
);


ALTER TABLE public.tbl_conf OWNER TO foods;

--
-- Name: tbl_conf_conf_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.tbl_conf ALTER COLUMN conf_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tbl_conf_conf_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_cuisine; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.tbl_cuisine (
    cuisine_id integer NOT NULL,
    cuisine_name character varying(200) NOT NULL
);


ALTER TABLE public.tbl_cuisine OWNER TO foods;

--
-- Name: tbl_cuisine_cuisine_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.tbl_cuisine ALTER COLUMN cuisine_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tbl_cuisine_cuisine_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_customer_review; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.tbl_customer_review (
    review_id integer NOT NULL,
    user_id integer NOT NULL,
    review_text character varying(500) NOT NULL
);


ALTER TABLE public.tbl_customer_review OWNER TO foods;

--
-- Name: tbl_customer_review_review_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.tbl_customer_review ALTER COLUMN review_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tbl_customer_review_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_dish_classification; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.tbl_dish_classification (
    dish_class_id integer NOT NULL,
    dish_class_name character varying(100) NOT NULL,
    dish_css_class character varying(50),
    is_active character varying(5)
);


ALTER TABLE public.tbl_dish_classification OWNER TO foods;

--
-- Name: tbl_dish_classification_dish_class_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.tbl_dish_classification ALTER COLUMN dish_class_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tbl_dish_classification_dish_class_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_menu; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.tbl_menu (
    menu_dish_id integer NOT NULL,
    menu_dish_name character varying(100) NOT NULL,
    menu_dish_cost numeric(10,2) NOT NULL,
    menu_cuisine_id integer NOT NULL,
    menu_dish_class_id integer NOT NULL,
    menu_dish_description character varying(500),
    menu_dish_pic_path character varying(500),
    prog_name character varying(150),
    is_active character varying(5),
    menu_extras character varying(10000),
    menu_dish_seq integer
);


ALTER TABLE public.tbl_menu OWNER TO foods;

--
-- Name: tbl_menu_menu_dish_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.tbl_menu ALTER COLUMN menu_dish_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tbl_menu_menu_dish_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_quantity_metrics; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.tbl_quantity_metrics (
    metric_id integer NOT NULL,
    metric_name character varying(20) NOT NULL
);


ALTER TABLE public.tbl_quantity_metrics OWNER TO foods;

--
-- Name: tbl_quantity_metrics_metric_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.tbl_quantity_metrics ALTER COLUMN metric_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tbl_quantity_metrics_metric_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_recipe; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.tbl_recipe (
    recipe_id integer NOT NULL,
    recipe_name character varying(200) NOT NULL,
    cuisine_id integer NOT NULL,
    recipe_created_by character varying(50) NOT NULL,
    recipe_updated_by character varying(50) NOT NULL,
    recipe_created_date timestamp without time zone,
    recipe_updated_date timestamp without time zone,
    recipe_description character varying(2000)
);


ALTER TABLE public.tbl_recipe OWNER TO foods;

--
-- Name: tbl_recipe_ingredients; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.tbl_recipe_ingredients (
    ingre_id integer NOT NULL,
    recipe_id integer NOT NULL,
    ingre_name character varying(200) NOT NULL,
    ingre_quantity integer NOT NULL,
    metric_id integer NOT NULL
);


ALTER TABLE public.tbl_recipe_ingredients OWNER TO foods;

--
-- Name: tbl_recipe_ingredients_ingre_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.tbl_recipe_ingredients ALTER COLUMN ingre_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tbl_recipe_ingredients_ingre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_recipe_recipe_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.tbl_recipe ALTER COLUMN recipe_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tbl_recipe_recipe_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_sub_menu; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.tbl_sub_menu (
    menu_items_id integer NOT NULL,
    menu_dish_id integer NOT NULL,
    menu_dish_name character varying(500) NOT NULL,
    order_item_price numeric(10,2) NOT NULL,
    is_active character varying(5)
);


ALTER TABLE public.tbl_sub_menu OWNER TO foods;

--
-- Name: tbl_sub_menu_menu_items_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.tbl_sub_menu ALTER COLUMN menu_items_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tbl_sub_menu_menu_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.tbl_user (
    user_id integer NOT NULL,
    user_name character varying(200) NOT NULL,
    user_password character varying(500) NOT NULL,
    user_first_name character varying(200) NOT NULL,
    user_last_name character varying(200) NOT NULL,
    user_gender character varying(10),
    user_customer_type character varying(50),
    user_business_name character varying(500)
);


ALTER TABLE public.tbl_user OWNER TO foods;

--
-- Name: tbl_user_contact_info; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.tbl_user_contact_info (
    user_contact_id integer NOT NULL,
    user_id integer NOT NULL,
    user_contact_type_id integer NOT NULL,
    user_contact_value character varying(500) NOT NULL,
    user_contact_default boolean
);


ALTER TABLE public.tbl_user_contact_info OWNER TO foods;

--
-- Name: tbl_user_contact_info_user_contact_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.tbl_user_contact_info ALTER COLUMN user_contact_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tbl_user_contact_info_user_contact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user_contact_type; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.tbl_user_contact_type (
    user_contact_type_id integer NOT NULL,
    user_contact_type_value character varying(100) NOT NULL
);


ALTER TABLE public.tbl_user_contact_type OWNER TO foods;

--
-- Name: tbl_user_contact_type_user_contact_type_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.tbl_user_contact_type ALTER COLUMN user_contact_type_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tbl_user_contact_type_user_contact_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user_order; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.tbl_user_order (
    order_id integer NOT NULL,
    user_id integer NOT NULL,
    order_date timestamp without time zone NOT NULL,
    order_total double precision,
    user_name character varying(100),
    acc_name character varying(150),
    acc_room_no character varying(4)
);


ALTER TABLE public.tbl_user_order OWNER TO foods;

--
-- Name: tbl_user_order_items; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.tbl_user_order_items (
    order_items_id integer NOT NULL,
    order_id integer NOT NULL,
    order_item_id integer NOT NULL,
    order_item_quantity integer NOT NULL,
    order_item_price double precision NOT NULL
);


ALTER TABLE public.tbl_user_order_items OWNER TO foods;

--
-- Name: tbl_user_order_items_order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.tbl_user_order_items ALTER COLUMN order_items_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tbl_user_order_items_order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user_order_order_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.tbl_user_order ALTER COLUMN order_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tbl_user_order_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_user_user_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.tbl_user ALTER COLUMN user_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tbl_user_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_website_hit; Type: TABLE; Schema: public; Owner: foods
--

CREATE TABLE public.tbl_website_hit (
    hit_id integer NOT NULL,
    ip_addr character varying(15) NOT NULL,
    device_type character varying(20),
    browser character varying(20),
    osname character varying(20),
    country character varying(20),
    city character varying(20),
    isp character varying(100),
    visitor_date timestamp without time zone
);


ALTER TABLE public.tbl_website_hit OWNER TO foods;

--
-- Name: tbl_website_hit_hit_id_seq; Type: SEQUENCE; Schema: public; Owner: foods
--

ALTER TABLE public.tbl_website_hit ALTER COLUMN hit_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tbl_website_hit_hit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: django_site django_site_domain_a2e37b91_uniq; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain);


--
-- Name: django_site django_site_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_pkey PRIMARY KEY (id);


--
-- Name: indian_breakfastmenuitem indian_breakfastmenuitem_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.indian_breakfastmenuitem
    ADD CONSTRAINT indian_breakfastmenuitem_pkey PRIMARY KEY (menu_dish_id);


--
-- Name: indian_configuration indian_configuration_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.indian_configuration
    ADD CONSTRAINT indian_configuration_pkey PRIMARY KEY (conf_id);


--
-- Name: tbl_app_conf tbl_app_conf_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_app_conf
    ADD CONSTRAINT tbl_app_conf_pkey PRIMARY KEY (app_conf_id);


--
-- Name: tbl_conf tbl_conf_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_conf
    ADD CONSTRAINT tbl_conf_pkey PRIMARY KEY (conf_id);


--
-- Name: tbl_cuisine tbl_cuisine_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_cuisine
    ADD CONSTRAINT tbl_cuisine_pkey PRIMARY KEY (cuisine_id);


--
-- Name: tbl_customer_review tbl_customer_review_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_customer_review
    ADD CONSTRAINT tbl_customer_review_pkey PRIMARY KEY (review_id);


--
-- Name: tbl_dish_classification tbl_dish_classification_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_dish_classification
    ADD CONSTRAINT tbl_dish_classification_pkey PRIMARY KEY (dish_class_id);


--
-- Name: tbl_menu tbl_menu_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_menu
    ADD CONSTRAINT tbl_menu_pkey PRIMARY KEY (menu_dish_id);


--
-- Name: tbl_quantity_metrics tbl_quantity_metrics_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_quantity_metrics
    ADD CONSTRAINT tbl_quantity_metrics_pkey PRIMARY KEY (metric_id);


--
-- Name: tbl_recipe_ingredients tbl_recipe_ingredients_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_recipe_ingredients
    ADD CONSTRAINT tbl_recipe_ingredients_pkey PRIMARY KEY (ingre_id);


--
-- Name: tbl_recipe tbl_recipe_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_recipe
    ADD CONSTRAINT tbl_recipe_pkey PRIMARY KEY (recipe_id);


--
-- Name: tbl_sub_menu tbl_sub_menu_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_sub_menu
    ADD CONSTRAINT tbl_sub_menu_pkey PRIMARY KEY (menu_items_id);


--
-- Name: tbl_user_contact_info tbl_user_contact_info_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_user_contact_info
    ADD CONSTRAINT tbl_user_contact_info_pkey PRIMARY KEY (user_contact_id);


--
-- Name: tbl_user_contact_type tbl_user_contact_type_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_user_contact_type
    ADD CONSTRAINT tbl_user_contact_type_pkey PRIMARY KEY (user_contact_type_id);


--
-- Name: tbl_user_order_items tbl_user_order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_user_order_items
    ADD CONSTRAINT tbl_user_order_items_pkey PRIMARY KEY (order_items_id);


--
-- Name: tbl_user_order tbl_user_order_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_user_order
    ADD CONSTRAINT tbl_user_order_pkey PRIMARY KEY (order_id);


--
-- Name: tbl_user tbl_user_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_user
    ADD CONSTRAINT tbl_user_pkey PRIMARY KEY (user_id);


--
-- Name: tbl_website_hit tbl_website_hit_pkey; Type: CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_website_hit
    ADD CONSTRAINT tbl_website_hit_pkey PRIMARY KEY (hit_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: foods
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: foods
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: foods
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: foods
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: foods
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: foods
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: foods
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: foods
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: foods
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: foods
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: foods
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: foods
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: foods
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: django_site_domain_a2e37b91_like; Type: INDEX; Schema: public; Owner: foods
--

CREATE INDEX django_site_domain_a2e37b91_like ON public.django_site USING btree (domain varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tbl_recipe fk_cuisine; Type: FK CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_recipe
    ADD CONSTRAINT fk_cuisine FOREIGN KEY (cuisine_id) REFERENCES public.tbl_cuisine(cuisine_id);


--
-- Name: tbl_menu fk_menu_classification_id; Type: FK CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_menu
    ADD CONSTRAINT fk_menu_classification_id FOREIGN KEY (menu_dish_class_id) REFERENCES public.tbl_dish_classification(dish_class_id);


--
-- Name: tbl_menu fk_menu_cuisine_id; Type: FK CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_menu
    ADD CONSTRAINT fk_menu_cuisine_id FOREIGN KEY (menu_cuisine_id) REFERENCES public.tbl_cuisine(cuisine_id);


--
-- Name: tbl_sub_menu fk_menu_item_id; Type: FK CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_sub_menu
    ADD CONSTRAINT fk_menu_item_id FOREIGN KEY (menu_dish_id) REFERENCES public.tbl_menu(menu_dish_id);


--
-- Name: tbl_user_order_items fk_order_item_id; Type: FK CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_user_order_items
    ADD CONSTRAINT fk_order_item_id FOREIGN KEY (order_id) REFERENCES public.tbl_user_order(order_id);


--
-- Name: tbl_user_order_items fk_order_menu_id; Type: FK CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_user_order_items
    ADD CONSTRAINT fk_order_menu_id FOREIGN KEY (order_item_id) REFERENCES public.tbl_menu(menu_dish_id);


--
-- Name: tbl_recipe_ingredients fk_quantity_metrics; Type: FK CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_recipe_ingredients
    ADD CONSTRAINT fk_quantity_metrics FOREIGN KEY (metric_id) REFERENCES public.tbl_quantity_metrics(metric_id);


--
-- Name: tbl_recipe_ingredients fk_recipe; Type: FK CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_recipe_ingredients
    ADD CONSTRAINT fk_recipe FOREIGN KEY (recipe_id) REFERENCES public.tbl_recipe(recipe_id);


--
-- Name: tbl_user_contact_info fk_user_contact_type; Type: FK CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_user_contact_info
    ADD CONSTRAINT fk_user_contact_type FOREIGN KEY (user_contact_type_id) REFERENCES public.tbl_user_contact_type(user_contact_type_id);


--
-- Name: tbl_user_contact_info fk_user_id; Type: FK CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_user_contact_info
    ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES public.tbl_user(user_id);


--
-- Name: tbl_user_order fk_user_order_id; Type: FK CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_user_order
    ADD CONSTRAINT fk_user_order_id FOREIGN KEY (user_id) REFERENCES public.tbl_user(user_id);


--
-- Name: tbl_customer_review fk_user_review_id; Type: FK CONSTRAINT; Schema: public; Owner: foods
--

ALTER TABLE ONLY public.tbl_customer_review
    ADD CONSTRAINT fk_user_review_id FOREIGN KEY (user_id) REFERENCES public.tbl_user(user_id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

GRANT USAGE ON SCHEMA public TO kholod;


--
-- Name: TABLE auth_group; Type: ACL; Schema: public; Owner: foods
--

GRANT ALL ON TABLE public.auth_group TO kholod WITH GRANT OPTION;


--
-- Name: TABLE auth_group_permissions; Type: ACL; Schema: public; Owner: foods
--

GRANT ALL ON TABLE public.auth_group_permissions TO kholod WITH GRANT OPTION;


--
-- Name: TABLE auth_permission; Type: ACL; Schema: public; Owner: foods
--

GRANT ALL ON TABLE public.auth_permission TO kholod WITH GRANT OPTION;


--
-- Name: TABLE auth_user; Type: ACL; Schema: public; Owner: foods
--

GRANT ALL ON TABLE public.auth_user TO kholod WITH GRANT OPTION;


--
-- Name: TABLE auth_user_groups; Type: ACL; Schema: public; Owner: foods
--

GRANT ALL ON TABLE public.auth_user_groups TO kholod WITH GRANT OPTION;


--
-- Name: TABLE auth_user_user_permissions; Type: ACL; Schema: public; Owner: foods
--

GRANT ALL ON TABLE public.auth_user_user_permissions TO kholod WITH GRANT OPTION;


--
-- Name: TABLE django_admin_log; Type: ACL; Schema: public; Owner: foods
--

GRANT ALL ON TABLE public.django_admin_log TO kholod WITH GRANT OPTION;


--
-- Name: TABLE django_content_type; Type: ACL; Schema: public; Owner: foods
--

GRANT ALL ON TABLE public.django_content_type TO kholod WITH GRANT OPTION;


--
-- Name: TABLE django_migrations; Type: ACL; Schema: public; Owner: foods
--

GRANT ALL ON TABLE public.django_migrations TO kholod WITH GRANT OPTION;


--
-- Name: TABLE django_session; Type: ACL; Schema: public; Owner: foods
--

GRANT ALL ON TABLE public.django_session TO kholod WITH GRANT OPTION;


--
-- Name: TABLE django_site; Type: ACL; Schema: public; Owner: foods
--

GRANT ALL ON TABLE public.django_site TO kholod WITH GRANT OPTION;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: kholod
--

ALTER DEFAULT PRIVILEGES FOR ROLE kholod REVOKE ALL ON TABLES  FROM kholod;
ALTER DEFAULT PRIVILEGES FOR ROLE kholod GRANT ALL ON TABLES  TO kholod WITH GRANT OPTION;


--
-- PostgreSQL database dump complete
--

